site_name: {{ cookiecutter.project_name }}
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - Installation: installation.md
    - Reference: reference.md

theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
          python:
              options:
                  show_root_heading: true
