name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}

      - name: Install Package
        run: |
            pip install pytest
            pip install .

      - name: Run tests
        run: python -m pytest .
